### ISSUE TITLE
calling `query.list_rows` for `SELECT *` queries can often fail

### ISSUE THREAD

**Issue by stevejpurves** [redivis/redivis-python#29]
I have had a couple of instances of this. A case in hand is when querying a file index table, eg.

```
q = dataset.query(f"""
    SELECT * from GISAssets A
""")

print("\nExpect a list of files")
gis_assets = q.list_rows()
```

Results in the following error:

![image](https://user-images.githubusercontent.com/1473646/204317837-150e1eca-7157-41fa-b99a-1de9530763bc.png)

I can work around this by specifying the column names explicitly, but perhaps non user facing columns should be maybe filtered out on `*` queries?

**Comment by imathews** [comment]
@stevejpurves thanks for opening this. The specific error here is due to the fact that named tuples can't use underscores in their property names, which is inconsistent with variable naming convention on Redivis (leading underscores are allowed). To remedy this, I just updated the `list_rows()` implementation to utilize a custom `Row` class rather than named tuple, now allowing for underscores in variable names. More info in the [v0.9.0 release notes](https://github.com/redivis/redivis-python/releases/tag/v0.9.0)

This should resolve the immediate issue here, but the behavior where `SELECT *` returns hidden variables is still present (though they can now just be ignored). This only occurs for unreleased tables, where we need to store a bit of additional information behind the scenes. Working on a fix for this as well, though this isn't specific to the python library — it can also happen when running queries on unreleased tables through the interface

**Comment by stevejpurves** [comment]
Thanks @imathews that should help my use case
